// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sqlg

import (
	"context"

	"github.com/gosoline-project/sqlg"
	mock "github.com/stretchr/testify/mock"
)

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type Client
func (_mock *Client) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Client_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Client_Expecter) Close() *Client_Close_Call {
	return &Client_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *Client_Close_Call) Run(run func()) *Client_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_Close_Call) Return(err error) *Client_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_Close_Call) RunAndReturn(run func() error) *Client_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Exec provides a mock function for the type Client
func (_mock *Client) Exec(ctx context.Context, query string, args ...any) (sqlg.Result, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, query, args)
	} else {
		tmpRet = _mock.Called(ctx, query)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 sqlg.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) (sqlg.Result, error)); ok {
		return returnFunc(ctx, query, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) sqlg.Result); ok {
		r0 = returnFunc(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sqlg.Result)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = returnFunc(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type Client_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *Client_Expecter) Exec(ctx interface{}, query interface{}, args ...interface{}) *Client_Exec_Call {
	return &Client_Exec_Call{Call: _e.mock.On("Exec",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *Client_Exec_Call) Run(run func(ctx context.Context, query string, args ...any)) *Client_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Client_Exec_Call) Return(v sqlg.Result, err error) *Client_Exec_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *Client_Exec_Call) RunAndReturn(run func(ctx context.Context, query string, args ...any) (sqlg.Result, error)) *Client_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type Client
func (_mock *Client) Get(ctx context.Context, dest any, query string, args ...any) error {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, dest, query, args)
	} else {
		tmpRet = _mock.Called(ctx, dest, query)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, string, ...any) error); ok {
		r0 = returnFunc(ctx, dest, query, args...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Client_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - dest any
//   - query string
//   - args ...any
func (_e *Client_Expecter) Get(ctx interface{}, dest interface{}, query interface{}, args ...interface{}) *Client_Get_Call {
	return &Client_Get_Call{Call: _e.mock.On("Get",
		append([]interface{}{ctx, dest, query}, args...)...)}
}

func (_c *Client_Get_Call) Run(run func(ctx context.Context, dest any, query string, args ...any)) *Client_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []any
		var variadicArgs []any
		if len(args) > 3 {
			variadicArgs = args[3].([]any)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *Client_Get_Call) Return(err error) *Client_Get_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_Get_Call) RunAndReturn(run func(ctx context.Context, dest any, query string, args ...any) error) *Client_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Qb provides a mock function for the type Client
func (_mock *Client) Qb() *sqlg.QueryBuilder {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Qb")
	}

	var r0 *sqlg.QueryBuilder
	if returnFunc, ok := ret.Get(0).(func() *sqlg.QueryBuilder); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlg.QueryBuilder)
		}
	}
	return r0
}

// Client_Qb_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Qb'
type Client_Qb_Call struct {
	*mock.Call
}

// Qb is a helper method to define mock.On call
func (_e *Client_Expecter) Qb() *Client_Qb_Call {
	return &Client_Qb_Call{Call: _e.mock.On("Qb")}
}

func (_c *Client_Qb_Call) Run(run func()) *Client_Qb_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_Qb_Call) Return(queryBuilder *sqlg.QueryBuilder) *Client_Qb_Call {
	_c.Call.Return(queryBuilder)
	return _c
}

func (_c *Client_Qb_Call) RunAndReturn(run func() *sqlg.QueryBuilder) *Client_Qb_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type Client
func (_mock *Client) Query(ctx context.Context, query string, args ...any) (*sqlg.Rows, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, query, args)
	} else {
		tmpRet = _mock.Called(ctx, query)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 *sqlg.Rows
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) (*sqlg.Rows, error)); ok {
		return returnFunc(ctx, query, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) *sqlg.Rows); ok {
		r0 = returnFunc(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlg.Rows)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = returnFunc(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type Client_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *Client_Expecter) Query(ctx interface{}, query interface{}, args ...interface{}) *Client_Query_Call {
	return &Client_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *Client_Query_Call) Run(run func(ctx context.Context, query string, args ...any)) *Client_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Client_Query_Call) Return(v *sqlg.Rows, err error) *Client_Query_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *Client_Query_Call) RunAndReturn(run func(ctx context.Context, query string, args ...any) (*sqlg.Rows, error)) *Client_Query_Call {
	_c.Call.Return(run)
	return _c
}

// Select provides a mock function for the type Client
func (_mock *Client) Select(ctx context.Context, dest any, query string, args ...any) error {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, dest, query, args)
	} else {
		tmpRet = _mock.Called(ctx, dest, query)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Select")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, string, ...any) error); ok {
		r0 = returnFunc(ctx, dest, query, args...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_Select_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Select'
type Client_Select_Call struct {
	*mock.Call
}

// Select is a helper method to define mock.On call
//   - ctx context.Context
//   - dest any
//   - query string
//   - args ...any
func (_e *Client_Expecter) Select(ctx interface{}, dest interface{}, query interface{}, args ...interface{}) *Client_Select_Call {
	return &Client_Select_Call{Call: _e.mock.On("Select",
		append([]interface{}{ctx, dest, query}, args...)...)}
}

func (_c *Client_Select_Call) Run(run func(ctx context.Context, dest any, query string, args ...any)) *Client_Select_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []any
		var variadicArgs []any
		if len(args) > 3 {
			variadicArgs = args[3].([]any)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *Client_Select_Call) Return(err error) *Client_Select_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_Select_Call) RunAndReturn(run func(ctx context.Context, dest any, query string, args ...any) error) *Client_Select_Call {
	_c.Call.Return(run)
	return _c
}
