// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sqlg

import (
	"github.com/gosoline-project/sqlg"
	mock "github.com/stretchr/testify/mock"
)

// NewDriver creates a new instance of Driver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDriver(t interface {
	mock.TestingT
	Cleanup(func())
}) *Driver {
	mock := &Driver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Driver is an autogenerated mock type for the Driver type
type Driver struct {
	mock.Mock
}

type Driver_Expecter struct {
	mock *mock.Mock
}

func (_m *Driver) EXPECT() *Driver_Expecter {
	return &Driver_Expecter{mock: &_m.Mock}
}

// GetDSN provides a mock function for the type Driver
func (_mock *Driver) GetDSN(settings *sqlg.Settings) string {
	ret := _mock.Called(settings)

	if len(ret) == 0 {
		panic("no return value specified for GetDSN")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(*sqlg.Settings) string); ok {
		r0 = returnFunc(settings)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Driver_GetDSN_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDSN'
type Driver_GetDSN_Call struct {
	*mock.Call
}

// GetDSN is a helper method to define mock.On call
//   - settings *sqlg.Settings
func (_e *Driver_Expecter) GetDSN(settings interface{}) *Driver_GetDSN_Call {
	return &Driver_GetDSN_Call{Call: _e.mock.On("GetDSN", settings)}
}

func (_c *Driver_GetDSN_Call) Run(run func(settings *sqlg.Settings)) *Driver_GetDSN_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *sqlg.Settings
		if args[0] != nil {
			arg0 = args[0].(*sqlg.Settings)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Driver_GetDSN_Call) Return(s string) *Driver_GetDSN_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Driver_GetDSN_Call) RunAndReturn(run func(settings *sqlg.Settings) string) *Driver_GetDSN_Call {
	_c.Call.Return(run)
	return _c
}
