// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sqlc

import (
	mock "github.com/stretchr/testify/mock"
)

// NewIsNullable creates a new instance of IsNullable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIsNullable(t interface {
	mock.TestingT
	Cleanup(func())
}) *IsNullable {
	mock := &IsNullable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IsNullable is an autogenerated mock type for the IsNullable type
type IsNullable struct {
	mock.Mock
}

type IsNullable_Expecter struct {
	mock *mock.Mock
}

func (_m *IsNullable) EXPECT() *IsNullable_Expecter {
	return &IsNullable_Expecter{mock: &_m.Mock}
}

// IsNullable provides a mock function for the type IsNullable
func (_mock *IsNullable) IsNullable() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsNullable")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// IsNullable_IsNullable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsNullable'
type IsNullable_IsNullable_Call struct {
	*mock.Call
}

// IsNullable is a helper method to define mock.On call
func (_e *IsNullable_Expecter) IsNullable() *IsNullable_IsNullable_Call {
	return &IsNullable_IsNullable_Call{Call: _e.mock.On("IsNullable")}
}

func (_c *IsNullable_IsNullable_Call) Run(run func()) *IsNullable_IsNullable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IsNullable_IsNullable_Call) Return(b bool) *IsNullable_IsNullable_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *IsNullable_IsNullable_Call) RunAndReturn(run func() bool) *IsNullable_IsNullable_Call {
	_c.Call.Return(run)
	return _c
}
