// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sqlg

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewLifecycleManager creates a new instance of LifecycleManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLifecycleManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *LifecycleManager {
	mock := &LifecycleManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// LifecycleManager is an autogenerated mock type for the LifecycleManager type
type LifecycleManager struct {
	mock.Mock
}

type LifecycleManager_Expecter struct {
	mock *mock.Mock
}

func (_m *LifecycleManager) EXPECT() *LifecycleManager_Expecter {
	return &LifecycleManager_Expecter{mock: &_m.Mock}
}

// GetId provides a mock function for the type LifecycleManager
func (_mock *LifecycleManager) GetId() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetId")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// LifecycleManager_GetId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetId'
type LifecycleManager_GetId_Call struct {
	*mock.Call
}

// GetId is a helper method to define mock.On call
func (_e *LifecycleManager_Expecter) GetId() *LifecycleManager_GetId_Call {
	return &LifecycleManager_GetId_Call{Call: _e.mock.On("GetId")}
}

func (_c *LifecycleManager_GetId_Call) Run(run func()) *LifecycleManager_GetId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *LifecycleManager_GetId_Call) Return(s string) *LifecycleManager_GetId_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *LifecycleManager_GetId_Call) RunAndReturn(run func() string) *LifecycleManager_GetId_Call {
	_c.Call.Return(run)
	return _c
}

// Purge provides a mock function for the type LifecycleManager
func (_mock *LifecycleManager) Purge(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Purge")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// LifecycleManager_Purge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Purge'
type LifecycleManager_Purge_Call struct {
	*mock.Call
}

// Purge is a helper method to define mock.On call
//   - ctx context.Context
func (_e *LifecycleManager_Expecter) Purge(ctx interface{}) *LifecycleManager_Purge_Call {
	return &LifecycleManager_Purge_Call{Call: _e.mock.On("Purge", ctx)}
}

func (_c *LifecycleManager_Purge_Call) Run(run func(ctx context.Context)) *LifecycleManager_Purge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *LifecycleManager_Purge_Call) Return(err error) *LifecycleManager_Purge_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *LifecycleManager_Purge_Call) RunAndReturn(run func(ctx context.Context) error) *LifecycleManager_Purge_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type LifecycleManager
func (_mock *LifecycleManager) Register(ctx context.Context) (string, any, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 string
	var r1 any
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, any, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) any); ok {
		r1 = returnFunc(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(any)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// LifecycleManager_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type LifecycleManager_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
func (_e *LifecycleManager_Expecter) Register(ctx interface{}) *LifecycleManager_Register_Call {
	return &LifecycleManager_Register_Call{Call: _e.mock.On("Register", ctx)}
}

func (_c *LifecycleManager_Register_Call) Run(run func(ctx context.Context)) *LifecycleManager_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *LifecycleManager_Register_Call) Return(s string, v any, err error) *LifecycleManager_Register_Call {
	_c.Call.Return(s, v, err)
	return _c
}

func (_c *LifecycleManager_Register_Call) RunAndReturn(run func(ctx context.Context) (string, any, error)) *LifecycleManager_Register_Call {
	_c.Call.Return(run)
	return _c
}
