// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sqlc

import (
	"context"
	"database/sql"

	"github.com/gosoline-project/sqlc"
	mock "github.com/stretchr/testify/mock"
)

// NewQuerier creates a new instance of Querier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *Querier {
	mock := &Querier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Querier is an autogenerated mock type for the Querier type
type Querier struct {
	mock.Mock
}

type Querier_Expecter struct {
	mock *mock.Mock
}

func (_m *Querier) EXPECT() *Querier_Expecter {
	return &Querier_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type Querier
func (_mock *Querier) Exec(ctx context.Context, query string, args ...any) (sqlc.Result, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, query, args)
	} else {
		tmpRet = _mock.Called(ctx, query)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 sqlc.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) (sqlc.Result, error)); ok {
		return returnFunc(ctx, query, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) sqlc.Result); ok {
		r0 = returnFunc(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sqlc.Result)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = returnFunc(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Querier_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type Querier_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *Querier_Expecter) Exec(ctx interface{}, query interface{}, args ...interface{}) *Querier_Exec_Call {
	return &Querier_Exec_Call{Call: _e.mock.On("Exec",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *Querier_Exec_Call) Run(run func(ctx context.Context, query string, args ...any)) *Querier_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Querier_Exec_Call) Return(v sqlc.Result, err error) *Querier_Exec_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *Querier_Exec_Call) RunAndReturn(run func(ctx context.Context, query string, args ...any) (sqlc.Result, error)) *Querier_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type Querier
func (_mock *Querier) Get(ctx context.Context, dest any, query string, args ...any) error {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, dest, query, args)
	} else {
		tmpRet = _mock.Called(ctx, dest, query)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, string, ...any) error); ok {
		r0 = returnFunc(ctx, dest, query, args...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Querier_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Querier_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - dest any
//   - query string
//   - args ...any
func (_e *Querier_Expecter) Get(ctx interface{}, dest interface{}, query interface{}, args ...interface{}) *Querier_Get_Call {
	return &Querier_Get_Call{Call: _e.mock.On("Get",
		append([]interface{}{ctx, dest, query}, args...)...)}
}

func (_c *Querier_Get_Call) Run(run func(ctx context.Context, dest any, query string, args ...any)) *Querier_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []any
		var variadicArgs []any
		if len(args) > 3 {
			variadicArgs = args[3].([]any)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *Querier_Get_Call) Return(err error) *Querier_Get_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Querier_Get_Call) RunAndReturn(run func(ctx context.Context, dest any, query string, args ...any) error) *Querier_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NamedExec provides a mock function for the type Querier
func (_mock *Querier) NamedExec(ctx context.Context, query string, arg any) (sqlc.Result, error) {
	ret := _mock.Called(ctx, query, arg)

	if len(ret) == 0 {
		panic("no return value specified for NamedExec")
	}

	var r0 sqlc.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) (sqlc.Result, error)); ok {
		return returnFunc(ctx, query, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) sqlc.Result); ok {
		r0 = returnFunc(ctx, query, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sqlc.Result)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, any) error); ok {
		r1 = returnFunc(ctx, query, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Querier_NamedExec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NamedExec'
type Querier_NamedExec_Call struct {
	*mock.Call
}

// NamedExec is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - arg any
func (_e *Querier_Expecter) NamedExec(ctx interface{}, query interface{}, arg interface{}) *Querier_NamedExec_Call {
	return &Querier_NamedExec_Call{Call: _e.mock.On("NamedExec", ctx, query, arg)}
}

func (_c *Querier_NamedExec_Call) Run(run func(ctx context.Context, query string, arg any)) *Querier_NamedExec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Querier_NamedExec_Call) Return(v sqlc.Result, err error) *Querier_NamedExec_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *Querier_NamedExec_Call) RunAndReturn(run func(ctx context.Context, query string, arg any) (sqlc.Result, error)) *Querier_NamedExec_Call {
	_c.Call.Return(run)
	return _c
}

// Prepare provides a mock function for the type Querier
func (_mock *Querier) Prepare(ctx context.Context, query string) (*sqlc.Stmt, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for Prepare")
	}

	var r0 *sqlc.Stmt
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*sqlc.Stmt, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *sqlc.Stmt); ok {
		r0 = returnFunc(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlc.Stmt)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Querier_Prepare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prepare'
type Querier_Prepare_Call struct {
	*mock.Call
}

// Prepare is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
func (_e *Querier_Expecter) Prepare(ctx interface{}, query interface{}) *Querier_Prepare_Call {
	return &Querier_Prepare_Call{Call: _e.mock.On("Prepare", ctx, query)}
}

func (_c *Querier_Prepare_Call) Run(run func(ctx context.Context, query string)) *Querier_Prepare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Querier_Prepare_Call) Return(v *sqlc.Stmt, err error) *Querier_Prepare_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *Querier_Prepare_Call) RunAndReturn(run func(ctx context.Context, query string) (*sqlc.Stmt, error)) *Querier_Prepare_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type Querier
func (_mock *Querier) Query(ctx context.Context, query string, args ...any) (*sqlc.Rows, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, query, args)
	} else {
		tmpRet = _mock.Called(ctx, query)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 *sqlc.Rows
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) (*sqlc.Rows, error)); ok {
		return returnFunc(ctx, query, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) *sqlc.Rows); ok {
		r0 = returnFunc(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlc.Rows)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = returnFunc(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Querier_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type Querier_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *Querier_Expecter) Query(ctx interface{}, query interface{}, args ...interface{}) *Querier_Query_Call {
	return &Querier_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *Querier_Query_Call) Run(run func(ctx context.Context, query string, args ...any)) *Querier_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Querier_Query_Call) Return(v *sqlc.Rows, err error) *Querier_Query_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *Querier_Query_Call) RunAndReturn(run func(ctx context.Context, query string, args ...any) (*sqlc.Rows, error)) *Querier_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRow provides a mock function for the type Querier
func (_mock *Querier) QueryRow(ctx context.Context, query string, args ...any) *sql.Row {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, query, args)
	} else {
		tmpRet = _mock.Called(ctx, query)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for QueryRow")
	}

	var r0 *sql.Row
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) *sql.Row); ok {
		r0 = returnFunc(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Row)
		}
	}
	return r0
}

// Querier_QueryRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRow'
type Querier_QueryRow_Call struct {
	*mock.Call
}

// QueryRow is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *Querier_Expecter) QueryRow(ctx interface{}, query interface{}, args ...interface{}) *Querier_QueryRow_Call {
	return &Querier_QueryRow_Call{Call: _e.mock.On("QueryRow",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *Querier_QueryRow_Call) Run(run func(ctx context.Context, query string, args ...any)) *Querier_QueryRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Querier_QueryRow_Call) Return(row *sql.Row) *Querier_QueryRow_Call {
	_c.Call.Return(row)
	return _c
}

func (_c *Querier_QueryRow_Call) RunAndReturn(run func(ctx context.Context, query string, args ...any) *sql.Row) *Querier_QueryRow_Call {
	_c.Call.Return(run)
	return _c
}

// Select provides a mock function for the type Querier
func (_mock *Querier) Select(ctx context.Context, dest any, query string, args ...any) error {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, dest, query, args)
	} else {
		tmpRet = _mock.Called(ctx, dest, query)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Select")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, string, ...any) error); ok {
		r0 = returnFunc(ctx, dest, query, args...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Querier_Select_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Select'
type Querier_Select_Call struct {
	*mock.Call
}

// Select is a helper method to define mock.On call
//   - ctx context.Context
//   - dest any
//   - query string
//   - args ...any
func (_e *Querier_Expecter) Select(ctx interface{}, dest interface{}, query interface{}, args ...interface{}) *Querier_Select_Call {
	return &Querier_Select_Call{Call: _e.mock.On("Select",
		append([]interface{}{ctx, dest, query}, args...)...)}
}

func (_c *Querier_Select_Call) Run(run func(ctx context.Context, dest any, query string, args ...any)) *Querier_Select_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []any
		var variadicArgs []any
		if len(args) > 3 {
			variadicArgs = args[3].([]any)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *Querier_Select_Call) Return(err error) *Querier_Select_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Querier_Select_Call) RunAndReturn(run func(ctx context.Context, dest any, query string, args ...any) error) *Querier_Select_Call {
	_c.Call.Return(run)
	return _c
}
