// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sqlc

import (
	mock "github.com/stretchr/testify/mock"
)

// NewSqler creates a new instance of Sqler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSqler(t interface {
	mock.TestingT
	Cleanup(func())
}) *Sqler {
	mock := &Sqler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Sqler is an autogenerated mock type for the Sqler type
type Sqler struct {
	mock.Mock
}

type Sqler_Expecter struct {
	mock *mock.Mock
}

func (_m *Sqler) EXPECT() *Sqler_Expecter {
	return &Sqler_Expecter{mock: &_m.Mock}
}

// ToSql provides a mock function for the type Sqler
func (_mock *Sqler) ToSql() (string, []any, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ToSql")
	}

	var r0 string
	var r1 []any
	var r2 error
	if returnFunc, ok := ret.Get(0).(func() (string, []any, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() []any); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]any)
		}
	}
	if returnFunc, ok := ret.Get(2).(func() error); ok {
		r2 = returnFunc()
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// Sqler_ToSql_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToSql'
type Sqler_ToSql_Call struct {
	*mock.Call
}

// ToSql is a helper method to define mock.On call
func (_e *Sqler_Expecter) ToSql() *Sqler_ToSql_Call {
	return &Sqler_ToSql_Call{Call: _e.mock.On("ToSql")}
}

func (_c *Sqler_ToSql_Call) Run(run func()) *Sqler_ToSql_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Sqler_ToSql_Call) Return(query string, params []any, err error) *Sqler_ToSql_Call {
	_c.Call.Return(query, params, err)
	return _c
}

func (_c *Sqler_ToSql_Call) RunAndReturn(run func() (string, []any, error)) *Sqler_ToSql_Call {
	_c.Call.Return(run)
	return _c
}
