// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/gosoline-project/sqlc"
	mock "github.com/stretchr/testify/mock"
)

// NewTx creates a new instance of Tx. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTx(t interface {
	mock.TestingT
	Cleanup(func())
}) *Tx {
	mock := &Tx{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Tx is an autogenerated mock type for the Tx type
type Tx struct {
	mock.Mock
}

type Tx_Expecter struct {
	mock *mock.Mock
}

func (_m *Tx) EXPECT() *Tx_Expecter {
	return &Tx_Expecter{mock: &_m.Mock}
}

// Commit provides a mock function for the type Tx
func (_mock *Tx) Commit() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Tx_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type Tx_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
func (_e *Tx_Expecter) Commit() *Tx_Commit_Call {
	return &Tx_Commit_Call{Call: _e.mock.On("Commit")}
}

func (_c *Tx_Commit_Call) Run(run func()) *Tx_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Tx_Commit_Call) Return(err error) *Tx_Commit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Tx_Commit_Call) RunAndReturn(run func() error) *Tx_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// Deadline provides a mock function for the type Tx
func (_mock *Tx) Deadline() (time.Time, bool) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Deadline")
	}

	var r0 time.Time
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func() (time.Time, bool)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	if returnFunc, ok := ret.Get(1).(func() bool); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// Tx_Deadline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deadline'
type Tx_Deadline_Call struct {
	*mock.Call
}

// Deadline is a helper method to define mock.On call
func (_e *Tx_Expecter) Deadline() *Tx_Deadline_Call {
	return &Tx_Deadline_Call{Call: _e.mock.On("Deadline")}
}

func (_c *Tx_Deadline_Call) Run(run func()) *Tx_Deadline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Tx_Deadline_Call) Return(deadline time.Time, ok bool) *Tx_Deadline_Call {
	_c.Call.Return(deadline, ok)
	return _c
}

func (_c *Tx_Deadline_Call) RunAndReturn(run func() (time.Time, bool)) *Tx_Deadline_Call {
	_c.Call.Return(run)
	return _c
}

// Done provides a mock function for the type Tx
func (_mock *Tx) Done() <-chan struct{} {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Done")
	}

	var r0 <-chan struct{}
	if returnFunc, ok := ret.Get(0).(func() <-chan struct{}); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}
	return r0
}

// Tx_Done_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Done'
type Tx_Done_Call struct {
	*mock.Call
}

// Done is a helper method to define mock.On call
func (_e *Tx_Expecter) Done() *Tx_Done_Call {
	return &Tx_Done_Call{Call: _e.mock.On("Done")}
}

func (_c *Tx_Done_Call) Run(run func()) *Tx_Done_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Tx_Done_Call) Return(valCh <-chan struct{}) *Tx_Done_Call {
	_c.Call.Return(valCh)
	return _c
}

func (_c *Tx_Done_Call) RunAndReturn(run func() <-chan struct{}) *Tx_Done_Call {
	_c.Call.Return(run)
	return _c
}

// Err provides a mock function for the type Tx
func (_mock *Tx) Err() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Err")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Tx_Err_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Err'
type Tx_Err_Call struct {
	*mock.Call
}

// Err is a helper method to define mock.On call
func (_e *Tx_Expecter) Err() *Tx_Err_Call {
	return &Tx_Err_Call{Call: _e.mock.On("Err")}
}

func (_c *Tx_Err_Call) Run(run func()) *Tx_Err_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Tx_Err_Call) Return(err error) *Tx_Err_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Tx_Err_Call) RunAndReturn(run func() error) *Tx_Err_Call {
	_c.Call.Return(run)
	return _c
}

// Exec provides a mock function for the type Tx
func (_mock *Tx) Exec(ctx context.Context, query string, args ...any) (sqlc.Result, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, query, args)
	} else {
		tmpRet = _mock.Called(ctx, query)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 sqlc.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) (sqlc.Result, error)); ok {
		return returnFunc(ctx, query, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) sqlc.Result); ok {
		r0 = returnFunc(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sqlc.Result)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = returnFunc(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Tx_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type Tx_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *Tx_Expecter) Exec(ctx interface{}, query interface{}, args ...interface{}) *Tx_Exec_Call {
	return &Tx_Exec_Call{Call: _e.mock.On("Exec",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *Tx_Exec_Call) Run(run func(ctx context.Context, query string, args ...any)) *Tx_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Tx_Exec_Call) Return(v sqlc.Result, err error) *Tx_Exec_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *Tx_Exec_Call) RunAndReturn(run func(ctx context.Context, query string, args ...any) (sqlc.Result, error)) *Tx_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type Tx
func (_mock *Tx) Get(ctx context.Context, dest any, query string, args ...any) error {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, dest, query, args)
	} else {
		tmpRet = _mock.Called(ctx, dest, query)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, string, ...any) error); ok {
		r0 = returnFunc(ctx, dest, query, args...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Tx_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Tx_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - dest any
//   - query string
//   - args ...any
func (_e *Tx_Expecter) Get(ctx interface{}, dest interface{}, query interface{}, args ...interface{}) *Tx_Get_Call {
	return &Tx_Get_Call{Call: _e.mock.On("Get",
		append([]interface{}{ctx, dest, query}, args...)...)}
}

func (_c *Tx_Get_Call) Run(run func(ctx context.Context, dest any, query string, args ...any)) *Tx_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []any
		var variadicArgs []any
		if len(args) > 3 {
			variadicArgs = args[3].([]any)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *Tx_Get_Call) Return(err error) *Tx_Get_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Tx_Get_Call) RunAndReturn(run func(ctx context.Context, dest any, query string, args ...any) error) *Tx_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NamedExec provides a mock function for the type Tx
func (_mock *Tx) NamedExec(ctx context.Context, query string, arg any) (sqlc.Result, error) {
	ret := _mock.Called(ctx, query, arg)

	if len(ret) == 0 {
		panic("no return value specified for NamedExec")
	}

	var r0 sqlc.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) (sqlc.Result, error)); ok {
		return returnFunc(ctx, query, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) sqlc.Result); ok {
		r0 = returnFunc(ctx, query, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sqlc.Result)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, any) error); ok {
		r1 = returnFunc(ctx, query, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Tx_NamedExec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NamedExec'
type Tx_NamedExec_Call struct {
	*mock.Call
}

// NamedExec is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - arg any
func (_e *Tx_Expecter) NamedExec(ctx interface{}, query interface{}, arg interface{}) *Tx_NamedExec_Call {
	return &Tx_NamedExec_Call{Call: _e.mock.On("NamedExec", ctx, query, arg)}
}

func (_c *Tx_NamedExec_Call) Run(run func(ctx context.Context, query string, arg any)) *Tx_NamedExec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Tx_NamedExec_Call) Return(v sqlc.Result, err error) *Tx_NamedExec_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *Tx_NamedExec_Call) RunAndReturn(run func(ctx context.Context, query string, arg any) (sqlc.Result, error)) *Tx_NamedExec_Call {
	_c.Call.Return(run)
	return _c
}

// Prepare provides a mock function for the type Tx
func (_mock *Tx) Prepare(ctx context.Context, query string) (*sqlc.Stmt, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for Prepare")
	}

	var r0 *sqlc.Stmt
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*sqlc.Stmt, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *sqlc.Stmt); ok {
		r0 = returnFunc(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlc.Stmt)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Tx_Prepare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prepare'
type Tx_Prepare_Call struct {
	*mock.Call
}

// Prepare is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
func (_e *Tx_Expecter) Prepare(ctx interface{}, query interface{}) *Tx_Prepare_Call {
	return &Tx_Prepare_Call{Call: _e.mock.On("Prepare", ctx, query)}
}

func (_c *Tx_Prepare_Call) Run(run func(ctx context.Context, query string)) *Tx_Prepare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Tx_Prepare_Call) Return(v *sqlc.Stmt, err error) *Tx_Prepare_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *Tx_Prepare_Call) RunAndReturn(run func(ctx context.Context, query string) (*sqlc.Stmt, error)) *Tx_Prepare_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type Tx
func (_mock *Tx) Query(ctx context.Context, query string, args ...any) (*sqlc.Rows, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, query, args)
	} else {
		tmpRet = _mock.Called(ctx, query)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 *sqlc.Rows
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) (*sqlc.Rows, error)); ok {
		return returnFunc(ctx, query, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) *sqlc.Rows); ok {
		r0 = returnFunc(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlc.Rows)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = returnFunc(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Tx_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type Tx_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *Tx_Expecter) Query(ctx interface{}, query interface{}, args ...interface{}) *Tx_Query_Call {
	return &Tx_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *Tx_Query_Call) Run(run func(ctx context.Context, query string, args ...any)) *Tx_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Tx_Query_Call) Return(v *sqlc.Rows, err error) *Tx_Query_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *Tx_Query_Call) RunAndReturn(run func(ctx context.Context, query string, args ...any) (*sqlc.Rows, error)) *Tx_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRow provides a mock function for the type Tx
func (_mock *Tx) QueryRow(ctx context.Context, query string, args ...any) *sql.Row {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, query, args)
	} else {
		tmpRet = _mock.Called(ctx, query)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for QueryRow")
	}

	var r0 *sql.Row
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) *sql.Row); ok {
		r0 = returnFunc(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Row)
		}
	}
	return r0
}

// Tx_QueryRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRow'
type Tx_QueryRow_Call struct {
	*mock.Call
}

// QueryRow is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *Tx_Expecter) QueryRow(ctx interface{}, query interface{}, args ...interface{}) *Tx_QueryRow_Call {
	return &Tx_QueryRow_Call{Call: _e.mock.On("QueryRow",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *Tx_QueryRow_Call) Run(run func(ctx context.Context, query string, args ...any)) *Tx_QueryRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Tx_QueryRow_Call) Return(row *sql.Row) *Tx_QueryRow_Call {
	_c.Call.Return(row)
	return _c
}

func (_c *Tx_QueryRow_Call) RunAndReturn(run func(ctx context.Context, query string, args ...any) *sql.Row) *Tx_QueryRow_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function for the type Tx
func (_mock *Tx) Rollback() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Tx_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type Tx_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
func (_e *Tx_Expecter) Rollback() *Tx_Rollback_Call {
	return &Tx_Rollback_Call{Call: _e.mock.On("Rollback")}
}

func (_c *Tx_Rollback_Call) Run(run func()) *Tx_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Tx_Rollback_Call) Return(err error) *Tx_Rollback_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Tx_Rollback_Call) RunAndReturn(run func() error) *Tx_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// Select provides a mock function for the type Tx
func (_mock *Tx) Select(ctx context.Context, dest any, query string, args ...any) error {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, dest, query, args)
	} else {
		tmpRet = _mock.Called(ctx, dest, query)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Select")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, string, ...any) error); ok {
		r0 = returnFunc(ctx, dest, query, args...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Tx_Select_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Select'
type Tx_Select_Call struct {
	*mock.Call
}

// Select is a helper method to define mock.On call
//   - ctx context.Context
//   - dest any
//   - query string
//   - args ...any
func (_e *Tx_Expecter) Select(ctx interface{}, dest interface{}, query interface{}, args ...interface{}) *Tx_Select_Call {
	return &Tx_Select_Call{Call: _e.mock.On("Select",
		append([]interface{}{ctx, dest, query}, args...)...)}
}

func (_c *Tx_Select_Call) Run(run func(ctx context.Context, dest any, query string, args ...any)) *Tx_Select_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []any
		var variadicArgs []any
		if len(args) > 3 {
			variadicArgs = args[3].([]any)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *Tx_Select_Call) Return(err error) *Tx_Select_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Tx_Select_Call) RunAndReturn(run func(ctx context.Context, dest any, query string, args ...any) error) *Tx_Select_Call {
	_c.Call.Return(run)
	return _c
}

// Value provides a mock function for the type Tx
func (_mock *Tx) Value(key any) any {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Value")
	}

	var r0 any
	if returnFunc, ok := ret.Get(0).(func(any) any); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	return r0
}

// Tx_Value_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Value'
type Tx_Value_Call struct {
	*mock.Call
}

// Value is a helper method to define mock.On call
//   - key any
func (_e *Tx_Expecter) Value(key interface{}) *Tx_Value_Call {
	return &Tx_Value_Call{Call: _e.mock.On("Value", key)}
}

func (_c *Tx_Value_Call) Run(run func(key any)) *Tx_Value_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Tx_Value_Call) Return(v any) *Tx_Value_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *Tx_Value_Call) RunAndReturn(run func(key any) any) *Tx_Value_Call {
	_c.Call.Return(run)
	return _c
}
